### ISSUE TITLE
output stderr only to logs, not to stderr of process

### ISSUE THREAD

**Issue by danielzfranklin** [rust-shell-script/rust_cmd_lib#23]
Hi, first off this is a great library that's helping me a lot.

I would ideally like a way to "capture" stderr such that it is logged but not sent to the stderr of the process running the rust code. Is this possible? I'd also like to do the same for stdout.

**Comment by rust-shell-script** [comment]
The library is already trying to capture stderr like this, see https://github.com/rust-shell-script/rust_cmd_lib#logging. Stdout is for piping only, which will not be captured in the log. However, you can redirect to stderr if you want to log it, e.g: 
```
        cmd_info!("Memory usage (free -m):");
        run_cmd!(free -m >&2)?;
    // to logs:
    INFO - memory usage (free -m):
    INFO -               total        used        free      shared  buff/cache   available
    INFO - Mem:           7709        2003        1070         656        4635        4675
    INFO - Swap:          8191          11        8180

```
I just found that the redirection part was not working as expected, a new commit just fixed that.

**Comment by danielzfranklin** [comment]
Thanks for fixing piping.

I'm not sure what you mean by stdout is for piping only. By default run_cmd connects the stdout of the spawned commands to the stdout of the rust process. Are you saying this is intended behavior? I was asking if I could send this to an info level log.

I'm using this in tests, and by default the stdout of the commands gets mixed in with the test results. I workaround this by using run_fun and ignoring the result.

**Comment by rust-shell-script** [comment]
I see, this seems related to `cargo test` command itself. From https://doc.rust-lang.org/cargo/commands/cargo-test.html#display-options, the stdout output should not appear in the console by default.  However, it looks like it only works for `println!` but not for `std::io::stdout().write_all(...)`. I checked the cargo source code, and it might be  due to thread local variables being used.

Anyway, I have submitted a new commit, which is working fine with `cargo test` command.
